### ISSUE TITLE
Imported target "JsonRpcCpp::Server" includes non-existent path  是为什么呢？

### ISSUE THREAD

**Issue by misiyu** [FISCO-BCOS/group-signature-server#8]

**Comment by misiyu** [comment]
ubuntu1604 亲测还需额外安装以下某个东西：
apt install libjsonrpccpp-dev libjsonrpccpp-tools 
apt install libcurl3
apt install libmicrohttpd-dev 
apt install libjsoncpp1 
apt install libjsoncpp-dev 
apt install libargtable2-0 
apt install libargtable2-dev

**Comment by Shareong** [comment]
Yes, all the dependencies required have been listed in readme after releasing v2.0.0.
